apiVersion: v1
kind: Service
metadata:
  namespace: saas-tenant-1
  name: saas-tenant-1-frontend-service
  annotations:
   service.beta.kubernetes.io/aws-load-balancer-type: nlb
   service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:427398298435:certificate/b571aa57-dead-49ce-9b72-e58f96150989
   service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
   service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
   external-dns.alpha.kubernetes.io/hostname: tenant-1.saas-tenant.cloud
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: saas-tenant-1-frontend