apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tenant
  namespace: default
spec:
  encryptedData:
    REACT_APP_AUTH0_CLIENT_ID: AgA7HWrrQXQ/BB/dPKWQEekI1ciheUNTmWf3wcNZbdgpDhGR4mxWJPcATaLK9O/V9ySnueArBm5jOvzYcd5HBUhdpkG5w01I5rHt+chRzEL2ZnUmvdyBdhztwO2/IdVccDsO027/eBy3veG/Kbt/tXzkSm8PUGFJ7McRn1gyjlcCt5MnROXkp0oovXBKpQrSDMQ1vSJskQ3M9h2cJwETh+owCe3MDNNbrm6Vz/pK4GZ2AB6Iua0iC+5xdpBDLVySKu5J1xi5Cvkut6yZB076tXiMQCJD32WdGVTMt0t8fkkEkadArRbjuotwHJj0BrJzThYtPb+IAhp1mdulJoqAU5oZdyvNy0mV5WCiufXNENNCdOG2hI/O3rzu1EHQlHPTai0VvV/q5+xQ860lYgJN+n7GMrf4VDu/JKdgxYzLxcKoelv4LsMsjAqJx//do4lY21MYeqIDxWrdU1VUkjhliNrDehkB7XOIjg0pk6rTdVSVhBf2T0srt0IT9etG/z18BZceK6R/N+bIAbfl5vwF+cjwS0Yhw3Y+A+D8VL6+qfP21/ysIrhLiCNoOo6qBV8prSjDWE/8ImmwFS5cjagVDJFLPklN6SBeG+QOxdc+gWyGNJxRwwTNry1Vtq7ilkHG5SBSoOolvCI4DtW1icyM4W73JdKraTvkV26AbPS3+VhN4efxs3VxGbPvHyi/Fi8tXv1vs7+RHYMYFHyQ4lci8sclGBPZnb5XkloMNSJVP8Ji3Q==
    REACT_APP_AUTH0_DOMAIN: AgC8p7zsqk7sN7PDQqQ5PBbHqnOo/R6fz8x1iRyAx2NDyFf1CU1a6SRPNvGE64trTJCHJA4eIpXx6KJRhl6XE9iUdFQ2+4tmKpTeaTKULg1RRwzitYxaVbJMma5yS8mATK5VgDEPqRAkteDvhtf/WO6IuqBDmzbSr0AuP9JujWBtQLLAf0Gaf0BNzNKkOx/prBQMBWL3MzKdzPVl9242l1NX+/DC2I37t5/am8qCujYdWPwc0aT7Dsr4DhAS+7bKvk4Mi3wwa7yAgU6xMYzYzo1hcn7u3x2ztGXrQAvXNzBBRU4vl0kDjSSi0ZjD6rzE35DCGYNZ2uvEBVdsSs/4Kv0ogyK8T/6mJ2dXVDMMy4M6nqan8xAZ8X7fxVjYclywCgd4eJ+oPV3aqRZw/wdwUjiYAaBPO3QVbhJO+rJc1Wz7WbDWYAOOBHG7Ue/8BmomsecMEtix+5RBY4SZk7ozef3bqd8DEZu9YsWornVibICKMiXCvj3Xs2bq1L1Za8pxZRuvZy+8Lk8R8W5/1AFM/DGv5cjFoV3d749W9S+BM207enXvpXBi37mNcH4X8Zmsvm1mxzqd7ml/NSwZt+fzyZGnBOpM3f5yIlpsv9c14DYIuk48e+o8iWuxWitjiir3r1sAcYuld1SsbX2NSXtmelzT6RCe3uDT5d7d+bElXNHfqQla0+IsOwm2bOnknRVDCavlAXyhUMyp9tgGwUJDgKkr+2zfOOe+NSoHJA==
  template:
    metadata:
      creationTimestamp: null
      name: tenant
      namespace: default
    type: Opaque

